### ISSUE TITLE
“期刊列表”页与“关于收支”页的一些问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#100]
1. “期刊列表”页
尽管 #98 中已经修复了大部分问题，但是好像还忘记了什么...?
> _2023-05_: Vol. 15
> 2023 年 08 月号

![image](https://github.com/TCA-Arknights/aneot/assets/48171809/f5195314-4dc1-44b5-a63c-d848102bb369)

2. “关于收支”页
末尾出现了重复的“再次感谢大家的支持”

![image](https://github.com/TCA-Arknights/aneot/assets/48171809/ecd9f8bc-74d6-4bdc-ba51-55ca51c5c625)

以上。

**Comment by yige-yigeren** [comment]
啊，草
