### ISSUE TITLE
关于“Vol. 15 - 2023 年 08 月号”的一个问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#102]
在[目录页](https://aneot.terrach.net/posts/2023-08)中，指向"特别专访：柞木不朽"的链接是无效的。

目录页中的链接为
> https://aneot.terrach.net/posts/2023-08/interview1.html
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/6eca47c5-7a9a-4c09-83bd-3333ee952d03)

实际应为（没有多出来的“1”）
> https://aneot.terrach.net/posts/2023-08/interview.html
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/847186d6-5db4-4671-b801-e757e153071c)

以上。

**Comment by TCA-Arknights** [comment]
感谢，已修复
