### ISSUE TITLE
建议优化暗色模式下 <eod/> 标签的显示

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#106]
如图，在暗色模式下，```<eod/>``` 标签显示并不清晰，希望在暗色模式下，此图像使用白色填充。
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/a823897f-c866-4269-acf0-88d568084627)

**Comment by yige-yigeren** [comment]
a038bb51215f18e4630720583ec5fc0aef15218a

临时处理方案，暂时没想好怎么拿theme的状态

**Comment by Baka632** [comment]
要不用SVG图像，然后根据主题自动填充颜色？

**Comment by yige-yigeren** [comment]
> 要不用SVG图像，然后根据主题自动填充颜色？

比较麻烦，我暂时没想好怎么搞，有想法可以开pr
