### ISSUE TITLE
关于主页的两个问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#111]
如下图所示：
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/d35c2b85-9a59-42e3-8600-fa7b587459bc)

1. 问题同 #96 （...啊？）
九月刊更新后，“最新一期”的信息仍然是八月刊的，而且这次是既没有改文章也没有改链接（乐）。

2. 画师信息仍然是八月刊的。

以上。

**Comment by yige-yigeren** [comment]
拾叁越堆越高力（悲）

保不齐什么地方就忘记改了，我下次建个清单挨个检查

**Comment by Baka632** [comment]
有的地方要不弄一点自动化？比如最新一期这种完全可以自动设置。

**Comment by yige-yigeren** [comment]
> 有的地方要不弄一点自动化？比如最新一期这种完全可以自动设置。

有设置自动化的事件都搞好力（
