### ISSUE TITLE
关于九月刊的两个问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#115]
1. 文章＂阿丽娜，我们想你＂中插图没有成功嵌入。
![IMG_20230928_223040](https://github.com/TCA-Arknights/aneot/assets/48171809/8dc4c63b-8f3e-410d-8bb8-f7f683b65e66)

2. 下载页中，九月刊的下载直链是无效的。
这可能是因为存放 PDF 文件的 GitHub 仓库中并没有九月刊的文件。

以上。

**Comment by Baka632** [comment]
Any updates?

**Comment by yige-yigeren** [comment]
啊，这两天在摸鱼（）没看见

**Comment by yige-yigeren** [comment]
19d3031c8dd94f6b0a4220272655b709c4197ffe
