### ISSUE TITLE
[Bug] “Vol. 16 - 2023 年 9 月号”中，“奥斯塔弄丢了无线耳机”一文的分类错误

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#118]
### alpha permissions?/内测用户？

- [ ] I am a alpha user/我是内测用户

### What devices seeing the problem on?/你所使用的设备？

Computer/电脑

### What browsers are you seeing the problem on?/你所使用的浏览器家族？(国产魔改浏览器请选择other）

chromium(eg. Chrome Edge Via)/（例如Chrome Edge Via）

### Browser UA/浏览器UA

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60

### Pages/页面

posts/2023-09/article3.html

### Expected behaviour/预期行为

“奥斯塔弄丢了无线耳机”一文应分类为“午间逸话”（根据期刊目录页的分类）
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/b6d0c175-79e7-48ba-b920-e077cae074c8)

### Actual behaviour/实际行为

“奥斯塔弄丢了无线耳机”一文被错误分类为“测试分区”
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/2f4afe46-79ac-48bf-837a-b81a79822110)

**Comment by yige-yigeren** [comment]
感谢，该问题是预载时默认均为测试分区，但在正式版忘记修改至对应分区了
