### ISSUE TITLE
[Bug] “期刊列表”页中，最新一期（Vol.17）的封面图像没有更新

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#122]
### alpha permissions?/内测用户？

- [ ] I am a alpha user/我是内测用户

### What devices seeing the problem on?/你所使用的设备？

Computer/电脑

### What browsers are you seeing the problem on?/你所使用的浏览器家族？(国产魔改浏览器请选择other）

chromium(eg. Chrome Edge Via)/（例如Chrome Edge Via）

### Browser UA/浏览器UA

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0

### Pages/页面

posts

### Expected behaviour/预期行为

“最新一期”的封面图像应于当期期刊吻合

### Actual behaviour/实际行为

“最新一期”的文字描述正确，但是封面图像仍为九月刊的图像
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/924f4d69-3f93-4de4-914c-397fd88a58ee)

**Comment by Baka632** [comment]
另外还有一个小小的疑问：本期期刊的 PDF 版本是有「特别专访」这个栏目的，但是网页版没有，这是预期行为吗？

**Comment by yige-yigeren** [comment]
> 另外还有一个小小的疑问：本期期刊的 PDF 版本是有「特别专访」这个栏目的，但是网页版没有，这是预期行为吗？

不是，实际上目前如公告所说很多staff无法参与正常制作，所以这期的发布其实是比较混乱的

**Comment by yige-yigeren** [comment]
我这段时间也很忙，晚点我会推送一个补丁解决这些问题

**Comment by Baka632** [comment]
「特别专访」确实加回来了，但是目录页没有这个栏目😂
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/44b55e9e-2520-4f8c-aeea-02cfd3e6e143)
