### ISSUE TITLE
[Bug] 在窗口宽度较宽的情况下，Vol.17 的文章《雪之所以是雪》会出现一个布局问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#125]
### alpha permissions?/内测用户？

- [ ] I am a alpha user/我是内测用户

### What devices seeing the problem on?/你所使用的设备？

Computer/电脑

### What browsers are you seeing the problem on?/你所使用的浏览器家族？(国产魔改浏览器请选择other）

chromium(eg. Chrome Edge Via)/（例如Chrome Edge Via）

### Browser UA/浏览器UA

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0

### Pages/页面

posts/2023-10/article2.html

### Expected behaviour/预期行为

文章正文与下方的「泰拉广告」应互不干扰，如下图所示：
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/90318f29-a85a-4067-a0ff-9b36c15e522d)

### Actual behaviour/实际行为

若窗口宽度较宽，文章正文中的图像会影响到下方「泰拉广告」中的元素布局，如下图所示：
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/e13b018e-5c0d-4110-8103-6c8001d63387)

---

若窗口宽度较窄，则无此问题。
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/0b9b33f6-f43a-4b56-86e2-c30045041097)

**Comment by Baka632** [comment]
另：本期（Vol.17）的「特别专访」栏目的写作日期不正确（2023年8月12日是 Vol.15 的写作日期，而不是 Vol.17 的写作日期）
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/0890fd8a-037f-493f-bc47-71c3da3b31af)

**Comment by yige-yigeren** [comment]
> 另：本期（Vol.17）的「特别专访」栏目的写作日期不正确（2023年8月12日是 Vol.15 的写作日期，而不是 Vol.17 的写作日期） ![image](https://user-images.githubusercontent.com/48171809/281117288-0890fd8a-037f-493f-bc47-71c3da3b31af.png)

因为本质上是CV过来的（擦汗）
