### ISSUE TITLE
[Bug] Vol.17 的目录页中，没有此期「特别专访」的信息

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#127]
### alpha permissions?/内测用户？

- [ ] I am a alpha user/我是内测用户

### Pages/页面

posts/2023-10/

### Expected behaviour/预期行为

期刊所属页面的信息都应当包含在目录页中。

### Actual behaviour/实际行为

Vol.17 的目录页缺少此期「特别专访」的信息，只有侧边栏才有。
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/7f740603-9e15-49f1-ab3e-785b5e214def)

**Comment by yige-yigeren** [comment]
有傻逼忘记改力（
