### ISSUE TITLE
[Bug] 有关 Vol.18 的两个问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#130]
### alpha permissions?/内测用户？

- [ ] I am a alpha user/我是内测用户

### Pages/页面

1. /posts
2. /download.html

### Expected behaviour/预期行为

1. 在期刊列表页中“往期回顾”里，Vol.18 的链接应当指向正确的页面
2. 在下载页中，Vol.18 相关的下载链接应当是符合预期的

### Actual behaviour/实际行为

1. 在期刊列表页中“往期回顾”里，Vol.18 的链接指向了 Vol.15
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/326be998-afa2-4c76-b553-46c725a1dd7b)

2. 在下载页中，单击 Vol.18 的 ```下载地址4``` 反而下载了 Vol.17 的 PDF 文件
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/deac3fd0-d32c-4f34-9cc9-e5efa07812e8)
而“网盘下载”链接并没有指向预期的页面，而是指向了"https://example.com"
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/a99762c3-29f6-4d6a-8d2e-11aca45e6a9a)

**Comment by yige-yigeren** [comment]
已修复，一些疏忽
