### ISSUE TITLE
[Bug] 关于主页画师信息的可视度问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#135]
### alpha permissions?/内测用户？

- [ ] I am a alpha user/我是内测用户

### What devices seeing the problem on?/你所使用的设备？

Computer/电脑

### What browsers are you seeing the problem on?/你所使用的浏览器家族？(国产魔改浏览器请选择other）

chromium(eg. Chrome Edge Via)/（例如Chrome Edge Via）

### Browser UA/浏览器UA

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

### Pages/页面

```/```

### Expected behaviour/预期行为

主页的画师信息应当清晰可见

### Actual behaviour/实际行为

主页画师信息的文本色与背景颜色相近，难以辨别
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/60aa088d-a8a6-43a9-92a3-cfe7a86ea64e)

---
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/4fc32bf6-2bf7-4d4b-9658-c6f39178fd38)

**Comment by yige-yigeren** [comment]
草，失策了

**Comment by yige-yigeren** [comment]
问题是，这玩意不是我写的（）
试着改了几个样式也不起效
@dscmarkw

**Comment by Baka632** [comment]
@yige-yigeren 
应该是改 ```docs/README.md``` 中的 ```heroAlt``` 吧？
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/8a5a77dc-a765-4f20-b57d-47a6b1c1d426)

**Comment by yige-yigeren** [comment]
> @yige-yigeren 应该是改 `docs/README.md` 中的 `heroAlt` 吧？ ![image](https://private-user-images.githubusercontent.com/48171809/293487079-8a5a77dc-a765-4f20-b57d-47a6b1c1d426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5OTk0OTEsIm5iZiI6MTcwMzk5OTE5MSwicGF0aCI6Ii80ODE3MTgwOS8yOTM0ODcwNzktOGE1YTc3ZGMtYTc2NS00ZjIwLWI1N2QtNDdhNmIxYzFkNDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA1MDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZTUzYmFjNTlhMDI5NzEwZGQzZDU3ZGE1YTU5YjRhODc1MWZmMDdiMjViNjYxYTkwNGE4YjVlMGQ5ZTRlOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0R7Hr28x3xmC9UdMGpT7fOX6W5zEs4Kr3fDePEb3oj8)

此处是用于修改当前杂志主题色的，我认为本期用白色比较合适（）

**Comment by Baka632** [comment]
那我就关这个 Issue 了
