### ISSUE TITLE
下载页面(download.md)标记出错 + 首页上“联系我们”的英文错误

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#67]
如下图所示，_Vol.03 2022年08月号_ 的下载链接处出现了意外的换行，使Markdown标记无效
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/4ceb38ef-6cf6-4f5a-9d62-3709a3914f6a)

这导致了下载页的显示不正常

![image](https://github.com/TCA-Arknights/aneot/assets/48171809/077b5b37-8203-4fb6-a85c-d48f4af923ca)

---

另外，首页的“联系我们”下的英文应为“Contact us” 而非 “Content us” ~（满足我们）~
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/13e710ce-9553-44b0-acc8-00879a37c387)

以上。

**Comment by yige-yigeren** [comment]
怎么有人更新链接动到前面的啊（望天）
拼写错误了，谢谢指正UwO

**Comment by yige-yigeren** [comment]
完事了，谢谢啦
