### ISSUE TITLE
“期刊列表”页与 Vol.12 中“干员秘闻”页的 Markdown 标记问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#69]
1. “期刊列表”页
当期期刊封面的样式标记中，似乎多出来了一个 ```>``` ，导致一些 Markdown 渲染器不能正确渲染页面。

![](https://github.com/TCA-Arknights/aneot/assets/48171809/cf594775-cd34-48f5-be2c-53632feaf717)

2. Vol.12 中的“干员秘闻”页
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/7bfe128e-a0ae-4e47-8c8b-f259c7f3e7d3)
如图所示，第七个问题的 Markdown 标记并没有与前面一样，在标题标记与表格标记间加入空格，这同样会使一些 Markdown 渲染器不能正确渲染页面。

![image](https://github.com/TCA-Arknights/aneot/assets/48171809/b59ed598-bef5-4fef-b4cb-a691aec4d5ff)

---

尽管这些标记不会影响到《回归线》网站的页面显示（你们究竟用的是什么Markdown解析库啊.jpg），但是对某些用户的影响是很大的 ~~（尤其是[AnEoT.Vintage](https://github.com/Baka632/aneot-vintage)项目）~~ ，所以还是希望对这些标记进行一些修改。

**Comment by yige-yigeren** [comment]
我们使用的是Vuepress默认的markdown解析，同时github好像也能处理这些qwq
虽然不影响网页显示，但已经热更修复了

**Comment by yige-yigeren** [comment]
又写了主页的一些改进，
我看某人还得受苦.jpg()
