### ISSUE TITLE
关于 favicon 的可视性问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#75]
如图，左边的**新图标**，其明显不如右边的**老图标**可视度高。
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/acb6bc38-c996-4544-99f3-f6aa6076e3f3)

左边的新图标太小了，影响观感，希望更换为以前的图标。

**Comment by yige-yigeren** [comment]
修改mainfest文件时使用了错误的logo
这个文件是计划用于声明pwa的

**Comment by TCA-Arknights** [comment]
> 如图，左边的**新图标**，其明显不如右边的**老图标**可视度高。 ![image](https://user-images.githubusercontent.com/48171809/255205090-acb6bc38-c996-4544-99f3-f6aa6076e3f3.png)
> 
> 左边的新图标太小了，影响观感，希望更换为以前的图标。

还有config.ts
