### ISSUE TITLE
关于＂Vol.13 - 2023年6月号＂的一些问题

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#89]
首先，目录页中有一处错误地将作者名当为文章名（此处应为"lost in 1083"）。

![IMG_20230726_115802.jpg](https://github.com/TCA-Arknights/aneot/assets/48171809/93e5b847-e2fd-4f74-b3a1-27a33627ef94)

其次，在文章＂lost in 1083＂中出现了一些意义不明的"bbscode i too long"字样，截图如下（部分）。

![IMG_20230726_120031.jpg](https://github.com/TCA-Arknights/aneot/assets/48171809/7a3114ee-28c2-45f8-9024-9a6fa9e361f3)

以上。

**Comment by yige-yigeren** [comment]
列文虎克是吧（笑哭）
不过还是谢谢了

**Comment by Baka632** [comment]
修好了，但没有完全修好😂
![IMG_20230726_120011.jpg](https://github.com/TCA-Arknights/aneot/assets/48171809/705d0d9d-849a-41b3-b7d1-710b75aedad7)

![IMG_20230726_120031.jpg](https://github.com/TCA-Arknights/aneot/assets/48171809/af8993f5-df27-41db-8b8c-1478b9b60f09)

**Comment by Baka632** [comment]
这个页面最开始有三处地方有这个问题，现在还有两处（

![IMG_20230726_143237.jpg](https://github.com/TCA-Arknights/aneot/assets/48171809/3394da05-846c-4982-b299-84b897ae979e)

![IMG_20230726_143223.jpg](https://github.com/TCA-Arknights/aneot/assets/48171809/de8a1166-79ca-417a-afc0-651c23c36ede)

**Comment by Baka632** [comment]
> 草，哪来的这玩意（）

估计是作者投稿的时候就有了，因为[nga上的这篇文章](https://g.nga.cn/read.php?tid=36142123&rand=814)也有这个问题（
![IMG_20230727_000814.jpg](https://github.com/TCA-Arknights/aneot/assets/48171809/24e122cd-c5f2-45ba-8d7e-e388bad1460e)
