### ISSUE TITLE
RSS 源似乎没有更新

### ISSUE THREAD

**Issue by Baka632** [TCA-Arknights/aneot#94]
目前，RSS 源中的文章还停留在 ```Vol. 11 - 2023 年 04 月号```

![image](https://github.com/TCA-Arknights/aneot/assets/48171809/6579682f-1688-4f04-9654-c537630abe31)

但是期刊已经更新到 ```Vol. 14 - 2023 年 07 月号``` 了...

**Comment by Baka632** [comment]
另：是否可以考虑为 RSS 源添加自定义样式以支持自定义字体？

现代 RSS 阅读器基本都能支持自定义样式。

效果图：
![image](https://github.com/TCA-Arknights/aneot/assets/48171809/40e1d6d0-9462-483c-9301-0f19cd0ccaee)

**Comment by yige-yigeren** [comment]
> 目前，RSS 源中的文章还停留在 `Vol. 11 - 2023 年 04 月号`
> 
> ![image](https://user-images.githubusercontent.com/48171809/260627359-6579682f-1688-4f04-9654-c537630abe31.png)
> 
> 但是期刊已经更新到 `Vol. 14 - 2023 年 07 月号` 了...

谢谢反馈，但截至目前该问题尚未找到其原因，本地构建的文件不存在问题。

目前该问题暂时划分为p4级别，暂不处于修复计划中。

**Comment by Baka632** [comment]
感谢回复，那我先关 Issue 了

**Comment by yige-yigeren** [comment]
该问题似乎已经修复，我也不知道怎么回事（

**Comment by yige-yigeren** [comment]
> 另：是否可以考虑为 RSS 源添加自定义样式以支持自定义字体？
> 
> 现代 RSS 阅读器基本都能支持自定义样式。
> 
> 效果图： ![image](https://user-images.githubusercontent.com/48171809/260627741-40e1d6d0-9462-483c-9301-0f19cd0ccaee.png)

可以详细说一下有什么思路吗？回归线的RSS是由框架自动生成的，干预这个过程可能比较难搞

**Comment by Baka632** [comment]
> 可以详细说一下有什么思路吗？回归线的RSS是由框架自动生成的，干预这个过程可能比较难搞

[AnEoT-Vintage](https://github.com/Baka632/aneot-vintage) 项目是这样做的：向每一条 RSS 的内容添加对 CSS 样式文件的引用。

代码实现在[这里](https://github.com/Baka632/aneot-vintage/blob/master/src/AnEoT.Vintage/Helpers/RssGenerationHelper.cs)（使用 C# 语言）

回归线网站的 RSS 生成器好像是 ```vuepress-plugin-feed2```，我找到一篇相关文档，可以参考一下。
[Feed 获取器](https://plugin-feed2.vuejs.press/zh/config/getter.html)
